defaultExercises = [
    ("Shoulder Press", "Shoulders", "shoulderpressdescription"),
    ("Lateral Raise", "Shoulders", "lateralraisedescription"),
    ("Rear Delt Flyes", "Shoulders", "rdfdescription"),
    ("Bench Press", "Chest", "benchpressdescription"),
    ("Chest Flyes", "Chest", "chestflyedescription"),
    ("Incline Dumbbell Press", "Chest", "inclinedbpressdescription"),
    ("Lat Pulldown", "Back", "latpulldowndescription"),
    ("Pull Up", "Back", "pullupdescription"),
    ("Seated Row", "Back", "seatedrowdescription"),
    ("Barbell Squat", "Legs", "squatdescription"),
    ("Leg Extension ", "Legs", "legextensiondescription"),
    ("Bicep Curl", "Biceps", "bicepcurldescription"),
    ("Hammer Curl", "Biceps", "hammercurldescription"),
    ("Tricep Pushdown", "Triceps", "triceppushdowndescription"),
    ("Tricep Extension", "Triceps", "tricepextensiondescription"),
    ("Deadlift", "Legs", "deadliftdescription"),
    ("Barbell Row", "Back", "barbellrowdescription"),
    ("Leg Curl", "Legs", "legcurldescription"),
    ("Calf Raise", "Legs", "calfraisedescription"),
    ("Dips", "Triceps", "dipsdescription"),
    ("Hip Thrust", "Glutes", "hipthrustdescription"),
    ("Leg Press", "Legs", "legpressdescription"),
]


